package i18n

object EnStrings : Strings {
    // Settings dialog
    override val settingsTitle = "Settings"
    override val apiKey = "API Key"
    override val model = "Model"
    override val maxTokensLabel = "Max Tokens (empty = default)"
    override val connectTimeout = "Connect Timeout (sec)"
    override val readTimeout = "Read Timeout (sec)"
    override val save = "Save"
    override val cancel = "Cancel"
    override val language = "Language"

    // Buttons
    override val send = "Send"
    override val sendAll = "Send All"
    override val clear = "Clear"
    override val clearAll = "Clear All"

    // Placeholders
    override val enterMessage = "Enter your message..."
    override val systemPromptGlobal = "System prompt (global)..."
    override val systemPromptPerChat = "System prompt (per-chat)..."
    override val constraintsPerChat = "Additional prompt (per-chat)..."
    override val constraintsPlaceholder = "Constraints (appended to prompt)..."
    override val maxTokensOverride = "Max tokens (override)..."
    override val jsonSchemaPlaceholder = "JSON Schema..."

    // Chat options
    override val optionStatistics = "Statistics"
    override val optionSystemPrompt = "System Prompt"
    override val optionConstraints = "Constraints"
    override val optionStopWords = "Stop Words"
    override val optionMaxTokens = "Max Tokens"
    override val optionResponseFormat = "Response Format"

    // Statistics tooltip
    override val lastRequest = "Last request"
    override val sessionTotal = "Session total"
    override val promptTokens = "Prompt Tokens"
    override val completionTokens = "Completion Tokens"
    override val totalTokens = "Total Tokens"
    override val promptTokensDesc = "Tokens sent in the request"
    override val completionTokensDesc = "Tokens generated by the model"
    override val totalTokensDesc = "Sum of prompt and completion tokens"
    override val allPromptTokensDesc = "All prompt tokens this session"
    override val allCompletionTokensDesc = "All completion tokens this session"
    override val allTotalTokensDesc = "All tokens consumed this session"

    // Parameterized
    override fun stopWordPlaceholder(index: Int) = "Stop ${index + 1}"
    override fun chatTitle(index: Int) = "Chat ${index + 1}"
    override fun temperatureValue(temp: String) = "Temperature: $temp"
    override fun lastStatsLine(p: Int, c: Int, t: Int) = "Last: P:$p C:$c T:$t"
    override fun totalStatsLine(p: Int, c: Int, t: Int) = "Total: P:$p C:$c T:$t"
}
